apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: remove-in-allns
spec:
  version: "{{ .TagName }}"
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-remove-in-allns/releases/download/{{ .TagName }}/darwin-amd64-{{ .TagName }}.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-remove-in-allns
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-remove-in-allns/releases/download/{{ .TagName }}/linux-amd64-{{ .TagName }}.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-remove-in-allns
  shortDescription: modify secret with implicit base64 translations
  caveats: |
    Usage:
      kubectl remove-in-allns secret-name -n kube-system
    
    Read the documentation at:
      https://github.com/rajatjindal/kubectl-remove-in-allns
  description: |
    Usage:
      kubectl remove-in-allns secret-name -n kube-system

      This plugin fetches the given secret manifest from the cluster, decodes 
      the payload, opens an editor to make changes, and applies the modified 
      manifest when done.
  homepage: https://github.com/rajatjindal/kubectl-remove-in-allns

